### ISSUE TITLE
'String' is not convertable to 'StringLiteralConvertable' - Error

### ISSUE THREAD

**Issue by petershaw** [JustHTTP/Just#10]
Hi, 

I am trying to replace a NSURLSession with Just. I am failing with a basic file upload.

Here is my code

```
        Just.post(
              urlString
            , files: [
                "filename": HTTPFile.URL(url, nil)
            ]
            , auth: (account.username, account.password)
            ) { (r: HTTPResult) in
                print("***** \(r.statusCode)")
                dump(r.text)
        }
```

But i cet a compile error *'String' is not convertable to 'StringLiteralConvertable'* on the **"filename"** string in line 4.

![screen shot 2015-08-08 at 01 15 28](https://cloud.githubusercontent.com/assets/475595/9147704/10bfd0f2-3d6b-11e5-957c-b3209810e7f2.png)

does someone has an idea?

**Comment by dduan** [comment]
Hi @petershaw experience shows that this kind of error is usually caused by optional values being used where their non-optional counter-parts are expected. Swift is not mature enough to report this accurately.

So, without seeing the rest of your code, I would guess that at least one of `url`, `account.username`, `account.password` is an optional that need unwrapping.
